# API Configuration
api:
  max_default_tokens: 1800
  build_failure: true
  # API keys should be set via environment variables
  # OPENAI_API_KEY
  # ANTHROPIC_API_KEY
  # COHERE_API_KEY

# Security Settings
security:
  ssl_verify: true
  rate_limit: 100  # requests per minute
  max_request_size: 10485760  # 10MB
  allowed_origins: ["https://localhost:3000", "https://yourdomain.com"]

# Paths
paths:
  dictionary_path: ${DICT_PATH:-/data/dicts}

# Logging
logging:
  level: INFO
  sensitive_fields: ["api_key", "password", "token", "secret"]
  mask_sensitive: true

# Cache Settings
cache:
  enabled: true
  ttl: 3600  # 1 hour
  max_size: 1000  # entries

# Optional: API Keys
# api_keys:
#   openai: your_api_key_here
