apiVersion: apps/v1
kind: Deployment
metadata:
  name: prompt-efficiency-api
  labels:
    app: prompt-efficiency
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prompt-efficiency
      component: api
  template:
    metadata:
      labels:
        app: prompt-efficiency
        component: api
    spec:
      containers:
      - name: api
        image: prompt-efficiency:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: prompt-efficiency-config
        - secretRef:
            name: prompt-efficiency-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: prompt-efficiency-api
  labels:
    app: prompt-efficiency
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: prompt-efficiency
    component: api 